In [1]:
import pandas as pd

excel_file = 'managers.xlsx'
to_out = 'Managers.xlsx'

df = pd.read_excel(excel_file)

In [2]:
df.head()

,url,name,school,degree,company,title,desc
0,https://www.linkedin.com/in/karlng/,Dr. Karl Ng,Harvard Business School,Executive Education,Proton,\nCompany Name\nMalaysia Digital Economy Corpo...,Driving the Malaysia's Data Economy. Facilita...
1,https://www.linkedin.com/in/siva-ramanathan-20...,Siva Ramanathan,Harvard Business School Executive Education,Executive Education,Primary Capital LLC (PC),ASEAN Advisor and Market Development Lead,Primary Capital LLC (PC) is a full service in...
2,https://www.linkedin.com/in/ming-seah-chee-4b2...,MING SEAH CHEE,NaN,NaN,NaN,NaN,NaN
3,https://www.linkedin.com/in/mei-khuen-wong-872...,Mei Khuen Wong,Harvard Business School,HBS Executive Education,NaN,\nCompany Name\nMaxis\n,"As the Head of BI & ERP, I’m responsible for ..."
4,https://www.linkedin.com/in/ghzali/,Muhammad Ghazali Abdul Aziz,HELP University,Master of Business Administration (M.B.A.),NaN,\nCompany Name\nHRDF- Human Resources Developm...,Provide strategic direction and leadership to...

In [3]:
df.shape

(20, 7)

In [3]:
xlsx = pd.ExcelFile(excel_file)
excel_sheets = []
for sheet in xlsx.sheet_names:
    excel_sheets.append(xlsx.parse(sheet))
# df = pd.concat(excel_sheets, ignore_index=True)
df = pd.concat(excel_sheets, ignore_index=False)

In [4]:
df.shape

(692, 7)

In [5]:
df

,url,name,school,degree,company,title,desc
0,https://www.linkedin.com/in/karlng/,Dr. Karl Ng,Harvard Business School,Executive Education,Proton,\nCompany Name\nMalaysia Digital Economy Corpo...,Driving the Malaysia's Data Economy. Facilita...
1,https://www.linkedin.com/in/siva-ramanathan-20...,Siva Ramanathan,Harvard Business School Executive Education,Executive Education,Primary Capital LLC (PC),ASEAN Advisor and Market Development Lead,Primary Capital LLC (PC) is a full service in...
2,https://www.linkedin.com/in/ming-seah-chee-4b2...,MING SEAH CHEE,NaN,NaN,NaN,NaN,NaN
3,https://www.linkedin.com/in/mei-khuen-wong-872...,Mei Khuen Wong,Harvard Business School,HBS Executive Education,NaN,\nCompany Name\nMaxis\n,"As the Head of BI & ERP, I’m responsible for ..."
4,https://www.linkedin.com/in/ghzali/,Muhammad Ghazali Abdul Aziz,HELP University,Master of Business Administration (M.B.A.),NaN,\nCompany Name\nHRDF- Human Resources Developm...,Provide strategic direction and leadership to...
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,https://www.linkedin.com/in/mui-han-koh/,Mui Han Koh,Harvard Business School Executive Education,Business Analytics and Big Data,ChangeDynamics Consulting,\n Ability to see the Messages in Your Misfor...,ChangeDynamics is a professional services fir...
7,https://www.linkedin.com/in/rony-ambrose-gobil...,Rony Ambrose Gobilee,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,https://www.linkedin.com/in/aniket-aranake-897...,Aniket Aranake,Stanford University,Master's degree,"CarePredict, Inc",Data Scientist,Created and delivered training courses in dat...
10,https://www.linkedin.com/in/karamjits/,Karamjit Singh,Bemidji State University,Mass Comm,Digital News Asia Sdn Bhd,"\n The AIM-DNA, 'Is That Innovation?' panel\n...",DNA covers the tech ecosystem in an analytica...
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,https://www.linkedin.com/in/bryan-loo-woi-lip-...,Bryan Loo Woi Lip,"University of Monash, Melbourne Australia",Bachelor of Science (B.S.),Loob Holding.,Chief Executive Officer,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,https://www.linkedin.com/in/simran-kaur-37154a82/,Simran Kaur,Harvard Business School Executive Education,Competing on Business Analytics and Big Data,JobStreet Education,General Manager,Currently leading a team on the ASEAN Data An...
15,https://www.linkedin.com/in/ryan-loo-4ba20311b/,Ryan Loo,Monash University,Bachelor of Mechatronics Engineering,Container Hotel Group,CEO & Co-Founder,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,https://www.linkedin.com/in/sarabmalaysia/,Sarabjeet Singh,Harvard Business School Executive Education,Competing on Business Analytics and Big Data,Accenture,\n Getting real with business leaders in Mala...,Responsibile for services sales and delivery ...
18,https://www.linkedin.com/in/wan-yon-shahima-wa...,Wan Yon Shahima Wan Othman,NaN,NaN,HRDF- Human Resources Development Fund Malaysia,Chief Operating Officer,NaN
19,https://www.linkedin.com/in/cm-vignaesvaran-je...,CM Vignaesvaran Jeyandran,National University of Malaysia,Bachelor of Business Administration - BBA,Customised solutions consultant,Senior Lead Consultant,NaN
0,https://www.linkedin.com/in/limcheehow/,Chee How Lim,Embry-Riddle Aeronautical University,Bachelor's Degree,Tapway Sdn Bhd,Chief Executive Officer,•\tLead and develop design activities for Eur...
1,https://www.linkedin.com/in/edwinlyw/,Edwin Lau,Harvard Business School Executive Education,Competing on Business Analytics and Big Data,QAPTURE Analytics,Director,Our vision is to help businesses to scale wit...
2,https://www.linkedin.com/in/lim-y-4ab8299a/,Lim Y.,Sunway College,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,https://www.linkedin.com/in/chin-kong-ng-654aab4/,Chin Kong Ng,Imperial College London,NaN,iSentric Sdn. Bhd.,Owner,NaN
6,https://www.linkedin.com/in/ckkoay/,C.K. Koay,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,https://www.linkedin.com/in/michellelim/,Michelle Lim,NaN,NaN,"iGene® Sdn. Bhd., an INFOVALLEY® Group of Comp...",\nCompany Name\nPETRONAS ICT Sdn Bhd\n,Appointed as the Head of Research and Develop...
...,...,...,...,...,...,...,...
2,https://www.linkedin.com/in/asleena-helmi-1611...,asleena helmi,NaN,NaN,Information and Security Research Laboratory (...,researcher,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://www.linkedin.com/in/cheng-soon-yeap-10...,Cheng Soon Yeap,Harvard Business School Executive Education,Competing on Business Analytics and Big Data,Enersave Engineering Systems Sdn Bhd,\nCompany Name\nPerbadanan Bekalan Air Pulau P...,"1. Team leader for design, planning, setup an..."
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,https://www.linkedin.com/in/wong-kee-ming-7829...,Wong Kee Ming,Technical Training Institute Kuala Lumpur,Electronic Engineering,Panasonic Manufacturing Malaysia Berhad,Assistant Director,NaN
8,https://www.linkedin.com/in/siti-sarah-johana-...,Siti Sarah Johana Mohd Said,NaN,NaN,Tenaga Nasional Berhad,Service Developer,NaN
9,https://www.linkedin.com/in/vernon-chua-2b22b7b6/,Vernon Chua,University of Melbourne,Bachelors of Information Systems,Innergia Labs Sdn Bhd,CEO,Our mission is to help traditional brick & mo...
10,https://www.linkedin.com/in/hong-sheng-kee-695...,Hong Sheng Kee,Universiti Tunku Abdul Rahman,Master in Science,Innergia Labs Sdn Bhd,Development Team Lead,RESPONSIBILITIES:\n\n\n\nCoordinate with sale...
11,https://www.linkedin.com/in/azlan-nazari-027a6...,Azlan Nazari,Harvard Business School Executive Education,HBS Malaysia Competing on Business Analytics a...,Tenaga Nasional Berhad,\n Visualising data: Busiest Airports in Mala...,CUSTOMER ANALYTICS\n\n-----------------------...
12,https://www.linkedin.com/in/mohamad-izhan-ayob...,Mohamad Izhan Ayob,University of Bristol,Bachelor’s Degree,Telekom Malaysia,General Manager,\n Was leading audit teams on assurance ...
13,https://www.linkedin.com/in/kengcheechan/,Chee-Chan Keng,Harvard Business School,Certificate of Attendance,Manulife,\nCompany Name\nTM Research & Development\n,* Lead multiple Agile teams consist of innova...
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,https://www.linkedin.com/in/gajenesh-nava-408a...,Gajenesh Nava,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,https://www.linkedin.com/in/hong-ling-goh-9323...,Hong Ling Goh,University Technology of Malaysia,Bachelor's degree,Intel,Senior System Analyst,NaN
0,https://www.linkedin.com/in/jim-daryl-teo-1936...,Jim Daryl Teo,The London School of Economics and Political S...,Bachelor of Science (BSc),webe digital,Director,NaN
1,https://www.linkedin.com/in/mohd-najib-bin-moh...,Mohd Najib Bin Mohammad,Harvard Business School,Executive Education,Tenaga Nasional Berhad,Business Development,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://www.linkedin.com/in/bachik-hussain-8b9...,Bachik Hussain,Universiti Sains Malaysia,Master,Motorola Solutions,\nCompany Name\nSanmina\n,- Ensure optimized use of Factory Space\n\n- ...
4,https://www.linkedin.com/in/kiow-kiow-chua-76b...,Kiow Kiow Chua,Science University of Malaysia,Bachelor of Computer Science,NaN,\nCompany Name\nIntel Corporation\n,NaN
5,https://www.linkedin.com/in/nicky-lim-5562b47/,Nicky Lim,NaN,NaN,NaN,NaN,NaN
6,https://www.linkedin.com/in/choon-kong-woo-871...,Choon Kong Woo,Johannes Gutenberg-Universität Mainz / Univers...,Doktor der Naturwissenschaften (Dr. rer. nat.)...,Universiti Sains Malaysia,\nCompany Name\nCardinal Health\n,"New Product Development, Pipeline Management,..."
7,https://www.linkedin.com/in/abd-wahid-bin-idri...,Abd Wahid bin Idris,Aberystwyth University,Bachelor’s Degree,Utusan Melayu ( M ) Berhad,General Manager Finance,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,https://www.linkedin.com/in/beng-keh-see-42a08...,Beng Keh See,The University of Birmingham,Bachelor's degree,Infineon Technologies,Senior Development Manager,NaN

In [6]:
df.to_excel(to_out)